### PR TITLE
add drone to run test, upload docker image to registry

### PR DESCRIPTION
**Pull request by oliver006**

### CODE REVIEW

**Comment by unfor19** [comment]
@oliver006 I've just tested your Docker image, and it doesn't work, I get some "missing module" errors
I'm not sure what's the issue, let me know if u need help with that.

**Comment by oliver006** [comment]
I just ran `docker build -t oliver006/es-test-data .` and it worked fine, what's the error you're seeing?

**Comment by unfor19** [comment]
This is what I get when I try to run your Docker image.

```bash
docker run --rm -it --network host oliver006/es-test-data  --es_url=http://localhost:9200 --batch_size=10000

Unable to find image 'oliver006/es-test-data:latest' locally
latest: Pulling from oliver006/es-test-data
801bfaa63ef2: Already exists 
8723b2b92bec: Already exists 
4e07029ccd64: Already exists 
594990504179: Already exists 
077e13ccccbd: Already exists 
3a6c175121c6: Pull complete 
f0fdff62e0c4: Pull complete 
69c5806039ea: Pull complete 
Digest: sha256:a16208f21ecb160c024e81d105b28a02e0a123b2463f3246a11672329c2e5719
Status: Downloaded newer image for oliver006/es-test-data:latest
Traceback (most recent call last):
  File "/app/es_test_data.py", line 3, in <module>
    import nest_asyncio
ModuleNotFoundError: No module named 'nest_asyncio'
```

When I use mine

```bash
docker run --rm -it --network host unfor19/es-test-data  --es_url=http://localhost:9200 --batch_size=10000

[I 210503 12:33:10 es_test_data:54] Trying to create index http://localhost:9200/test_data
```

Not sure what's the difference between the too, I think it requires further investigation.
Maybe you should push to DockerHub the image that works on your machine

**Comment by oliver006** [comment]
Thanks for letting me know. I just pushed an update and it should hopefully be fixed now.

**Pull request merged**
